### ISSUE TITLE
Guidance for Feedback

### ISSUE THREAD

**Issue by bleonar5** [psych-ds/psychds-docs#1]
The Psych-DS Docs website is in good enough shape to receive some feedback internally from the team. I'm happy to take feedback in whatever form is most comfortable for each individual. This might take the form of comments on this issue, creating a new branch on this repo and creating a pull request with the suggested changes, and email, a slack message, etc.

[Readthedocs site](https://psychds-docs.readthedocs.io/en/latest/)

### (1) General

- (a) My highest priority for feedback regards **clarity**. On the three main pages (so far), the landing page, the rules and conventions, and the getting started page, I would appreciate feedback about information flow, density, and accessibility. 
- (b) Are there any grammatical disfluencies or spelling errors?
- (c) Overall, do you feel that the docs give you a clear picture of what Psych-DS is, why it matters, why it's helpful, and how to use it?

### (2) Landing/Home Page

- (a) Does the landing page give a good overview of the project, does it require any graphics or videos to break up the blocks of text?
- (b) Does "motivation" section feel like it belongs on this page, or should it be broken off into its own page? Does it work well as text, or would it be better suited as a video of some sort, or both?
- (c) Does the amount of text on this page make your eyes roll into the back of your head?

### (3) Getting Started with Psych-DS

- (a) Is the Getting Started page sufficiently clear and helpful, does it fit the target audience of a junior researcher, or a researcher unfamiliar with digital data practices?
- (b) Is the sort of narrative format of walking through the process step by step the way to go? Is the text prohibitive? Would some simple screenshots help clarify things and cut through the clutter?

### (4) Rules and Conventions
- (a) Are you okay with the way the Rules and Conventions page is organized? Does the flow of the bulleted lists make sense, and does a bulleted list make sense for the info at hand?
- (b) When the rules and conventions link to a concept in the Schema Reference, does it provide the information that you need, or do the definitions that it links to leave you wanting more?

### (5) Schema Reference
- (a) What do you think of the aesthetics/formatting of the schema reference elements? They are a work in progress, I think, and can be improved. I feel that there could be more inter-linking between elements, like perhaps instead of having separate pages for definitions of certain files, rules for those files, and the errors that result from them, things could be better consolidated into single pages, or at least the separate pages should link to each other. This would take a little doing with the script that builds the schema reference from the schema model, but would perhaps be worth it in the long run.

**Comment by ianchandlercampbell** [comment]
First of all, this is a super impressive level of detail and an exemplary first draft of these materials! I particularly like the explanation/narrative style provided in (3) overall. Given the density and complexity of the information, I think we'll probably want to create a full Google Doc of just the main copy and work through each section one-by-one with suggestions and comments. @bleonar5 what I'd like to do is create the Google Doc , provide some in-depth feedback on each page, and then provide general feedback in response to your questions next week. @becky-gilbert can add to this Google Doc as well if she has comments/suggestions on the copy before providing the general feedback on this issue. Then, the three of us could meet at the end of next week to chat about the general feedback and other thoughts on the site. After the meeting, you could sit down and make revisions to the site incorporating our feedback. @bleonar5 how does that sound as a feedback process?

**Comment by bleonar5** [comment]
That sounds like a great plan!

**Comment by ianchandlercampbell** [comment]
Sounds good! I'll create the Google Doc and post it here on Monday!

Ian Chandler-Campbell, Ph.D.
Open-Source Community Manager, Children Helping Science
<https://childrenhelpingscience.com/>
Research Associate, Project GARDEN
<https://childrenhelpingscience.com/garden/scientists>
ianchandlercampbell.com
he/him/his

**Comment by becky-gilbert** [comment]
@ianchandlercampbell Sounds good to me! I'm going to make a google doc now because I'm reviewing the docs and need a place to put down my thoughts anyway. I'll share the link on Slack so that you can use it too. Or if you want to make one then I'll incorporate my comments into yours.

**Comment by ianchandlercampbell** [comment]
Sounds good!

**Comment by ianchandlercampbell** [comment]
@bleonar5 Checking in on this issue! Are we ready to close it or do you think you have some more work to do?
